LongStretch-v4/LongStretch/website/views.py
from turtle import title
from venv import create
from flask import Blueprint, render_template, request, flash, jsonify,redirect,url_for, abort
from .models import User,Post
from .forms import RegistrationForm,LoginForm,PostForm
from . import db,bcrypt
from flask_login import login_user, login_required, logout_user, current_user

views=Blueprint('views',__name__)


@views.route('/')
def home():
    return render_template("home.html",user=current_user)


@views.route('/news')
def news():
    return render_template("news.html",user=current_user)


@views.route('/drugs')
def drugs():
    return render_template("drugs.html",user=current_user)


@views.route('/tue')
def tue():
    return render_template("tue.html",user=current_user)


@views.route('/forum',methods=['GET','POST'])
def forum():
    page= request.args.get('page',1,type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template("forum.html",user=current_user,posts=posts)

@views.route('/aware')
def aware():
    return render_template("aware.html",user=current_user)

@views.route('/account/<string:username>')
def account(username):
    page = request.args.get('page',1,type=int)
    user=User.query.filter_by(username=username).first_or_404()
    image_file = url_for('static', filename='images/profile_pic/'+user.profile_pic)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template("account.html",user=current_user,img=image_file,page_user=user,posts = posts)

@views.route('/register',methods=['GET','POST'])
def register():
    form= RegistrationForm()
    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(username=form.username.data,email=form.email.data,password=hashed_password,sport=form.sport.data)
        db.session.add(user)
        db.session.commit()
        login_user(user,remember=False)
        flash(f'Your account has been created!','success')
        return redirect(url_for('views.home'))
    errors = [{'field': key, 'messages': form.errors[key]} for key in form.errors.keys()] if form.errors else []
    
    return render_template("register.html",user=current_user,form=form,errors=errors)


@views.route('/login', methods=['GET', 'POST'])
def login():
    form= LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=form.remember.data)
            next_page=request.args.get('next')
            flash(f'Logged in!','success')
            return redirect(next_page) if next_page else redirect(url_for('views.home'))
        else:
            flash("Login Unsuccessful. Please Check email and Password",'error')
    
    errors = [{'field': key, 'messages': form.errors[key]} for key in form.errors.keys()] if form.errors else []
    return render_template("login.html",user=current_user,form=form,errors=errors)

@views.route('/logout')
@login_required
def logout():
    logout_user()
    flash("Signed out",category='success')
    return redirect(url_for('views.login'))

@views.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form=PostForm()
    if form.validate_on_submit():
        post= Post(title=form.title.data,content=form.content.data,author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!','success')
        return redirect(url_for('views.forum'))
    return render_template("create_post.html",user=current_user,form=form,legend ="New Post")

@views.route("/post/<int:post_id>")
def post(post_id):
    post=Post.query.get_or_404(post_id)
    return render_template('post.html',post=post,user=current_user)

@views.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post=Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Post Updated!","success")
        return redirect(url_for('views.post', post_id=post.id))
    elif request.method =='GET':
        form.title.data= post.title
        form.content.data = post.content
    return render_template("create_post.html",user=current_user,form=form,legend="Update post")

@views.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('views.forum'))

LongStretch-v4/LongStretch/website/templates/account.html
{% extends "base.html" %}

{% block title%}{{page_user.username}}{%endblock%}

{% block content%}

<div class="container bg-light p-3">
    <div class="row">
        <div class="col-2">
            <img class="rounded-circle" src="{{img}}">
        </div>
        <div class="col-6 ms-auto align-items-middle">
            <h3 class="align-right">{{page_user.username}}</h3>
            <div class="row">{{page_user.email}}</div>
        </div>
    </div>
</div>

<div class="container bg-light mt-3 p-3">
    <div class="row p-3">
        <h3>Posts</h3>
        <hr class="divider">
    </div>
    <div class="row">
        <div class="container">
            {%for post in posts.items %}
            <div class="row">
                <article class="bg-white p-3 m-1 rounded">
                    <div class="container">
                        <div class="row">
                            <div class="col-1">
                                <img src="{{url_for('static',filename='images/profile_pic/'+post.author.profile_pic)}}"
                                    alt="img" class="rounded-circle" style="width: 50px;">
                            </div>
                            <div class="col-12">
                                <h3 class=""><a class="link-dark text-decoration-none"
                                        href="{{url_for('views.post', post_id=post.id)}}">{{post.title}}</a></h3>
                            </div>
                            <div class="col-2 ">
                                <a class="link-primary" style="text-decoration:none" href="#">{{post.author.username}}</a>
                            </div>
                            <div class="col-2 ms-auto">
                                {{post.date_posted.strftime('%Y-%m-%d')}}
                            </div>
                        </div>
                        <hr class="dropdown-divider">
                        <div class="row">
                            <p>{{post.content}}</p>
                        </div>
    
                    </div>
                </article>
            </div>
        {%endfor%}
        </div>
    </div>
    <div class="container">
        {% for page_num in posts.iter_pages(left_edge=1,right_edge=1, left_current=1,right_current=2) %}

        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{url_for('views.account',page=page_num,username=page_user.username)}}">{{page_num}}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{url_for('views.account',page=page_num,username=page_user.username)}}">{{page_num}}</a>
            {% endif %}
        {% else %}
        ...
        {%endif%}

        {%endfor%}
    </div>
</div>

{%endblock%}

LongStretch-v4/LongStretch/website/templates/aware.html
{% extends "base.html" %}
{% set active_page ='aware' %}

{% block content%}


{%endblock%}

LongStretch-v4/LongStretch/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}Dr~Dope{%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{{url_for('static',filename='main.css')}}">
    {% block css%}{%endblock%}
    
</head>
<body class="fs-5">

    <nav class="navbar navbar-expand-lg navbar-light p-3">
        <div class="container-fluid">
            <a href="/" class="navbar-brand">
                <img src="{{url_for('static',filename='images/logo.svg')}}" height="30" alt="DrAntiDope">
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse ms-4" id="navbarCollapse">
                <div class="navbar-nav">
                    <li class="hover-underline-animation nav-item dropdown me-4">
                        <a class=" {{'active' if active_page=='drugs' else ''}} nav-link dropdown" href="/drugs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Drugs
                        </a>
                        <ul class="dropdown-menu shadow">
                          <li><a class="dropdown-item" href="/drugs">Prohibited Drugs</a></li>
                          <li><a class="dropdown-item" href="/drugs">Alternatives Search</a></li>
                          <li><a class="dropdown-item" href="/drugs">Drugs</a></li>
                        </ul>
                    </li>
                    <!-- <a href="/drugs" class=" hover-underline-animation nav-item nav-link me-4 {{'active' if active_page=='drugs' else ''}}">Drugs</a> -->
                    <a href="/tue"   class=" hover-underline-animation nav-item nav-link me-4 {{'active' if active_page=='tue' else ''}}">TUE</a>
                    <a href="/aware" class=" hover-underline-animation nav-item nav-link me-4 {{'active' if active_page=='aware' else ''}}">Awareness</a>
                    <a href="/news"  class=" hover-underline-animation nav-item nav-link me-4 {{'active' if active_page=='news' else ''}}">News</a>
                    <a href="/forum" class=" hover-underline-animation nav-item nav-link {{'active' if active_page=='forum' else ''}}">Forum</a>
                </div>
                <div class="navbar-nav ms-auto">
                    {%if user.is_authenticated %}
                    <li class="nav-item dropdown me-4">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{user.username}}
                        </a>
                        <ul class="dropdown-menu shadow">
                          <li><a class="dropdown-item" href="{{url_for('views.account', username=user.username)}}">My Account</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="/logout">Log out</a></li>
                        </ul>
                      </li>
                    {%else%}
                    <a href="/login" class=" nav-item nav-link me-4">Sign in</a>
                    {%endif%}
                    <!-- <a href="/login"></a><button type="button" class="nav-item btn btn-outline-primary">Expert Support</button></a> -->
                    <button type="button" class="btn btn-outline-primary px-1 py-1"><a href="/" class="nav-item nav-link">Expert Support</a></button>
                </div>
            </div>
        </div>
    </nav>

    <!-- alert flashes -->
    {% with messages = get_flashed_messages(with_categories=true) %} 
        {% if messages %}
            {% for category, message in messages %}
                {% if category =='error' %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>{{message}}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% elif category =='success' %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>{{message}}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% else %}
                    <div class="alert alert-info alert-dismissible fade show" role="alert">
                        <strong>{{message}}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %} 
    {% endwith %}


    {% block content%}
    {%endblock%}


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

LongStretch-v4/LongStretch/website/templates/create_post.html
{% extends "base.html" %}


{% block content%}
<div class="container">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{legend}}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    
</div>
{%endblock%}

LongStretch-v4/LongStretch/website/templates/drugs.html
{% extends "base.html" %}
{% set active_page ='drugs' %}

{% block content%}


{%endblock%}

LongStretch-v4/LongStretch/website/templates/forum.html
{% extends "base.html" %}
{% set active_page ='forum' %}

{% block content%}
<div class="container">
    <div class="row">
        <div class="col-10">
            <div class="container">
                <div class="row">
                    <h2>Posts</h2>
                    <hr class="dropdown-divider">
                </div>
                {%for post in posts.items %}
                <div class="row">
                    <article class="bg-light p-4 m-1 rounded">
                        <div class="container m-0 p-0">
                            <div class="row">
                                <div class="col-1">
                                    <img src="{{url_for('static',filename='images/profile_pic/'+post.author.profile_pic)}}"
                                        alt="img" class="rounded-circle" style="width: 50px;">
                                </div>
                                <div class="col-12">
                                    <h3 class=""><a class="link-dark text-decoration-none"
                                            href="{{url_for('views.post', post_id=post.id)}}">{{post.title}}</a></h3>
                                </div>
                                <div class="col-2 ">
                                    <a class="link-primary" style="text-decoration:none"
                                        href="{{url_for('views.account', username=post.author.username)}}">{{post.author.username}}</a>
                                </div>
                                <div class="col-2 ms-auto">
                                    {{post.date_posted.strftime('%Y-%m-%d')}}
                                </div>
                            </div>
                            <hr class="dropdown-divider">
                            <div class="row">
                                <p>{{post.content}}</p>
                            </div>

                        </div>
                    </article>
                </div>
                {%endfor%}
            </div>
            <div class="container">
                {% for page_num in posts.iter_pages(left_edge=1,right_edge=1, left_current=1,right_current=2) %}

                {% if page_num %}
                    {% if posts.page == page_num %}
                        <a class="btn btn-info mb-4" href="{{url_for('views.forum',page=page_num)}}">{{page_num}}</a>
                    {% else %}
                        <a class="btn btn-outline-info mb-4" href="{{url_for('views.forum',page=page_num)}}">{{page_num}}</a>
                    {% endif %}
                {% else %}
                ...
                {%endif%}

                {%endfor%}
            </div>
        </div>



        <div class="col-2">
            <a name="" id="" class="btn btn-primary" href="/post/new" role="button">Add Post</a>
            <div class="container bg-light mt-3">

                <div class="row">
                    Popular Topics
                    <hr class="divider">
                </div>


            </div>
        </div>
    </div>


</div>
{%endblock%}

LongStretch-v4/LongStretch/website/templates/home.html
{% extends "base.html" %}
{% set active_page ='home' %}

{% block content%}


{%endblock%}

LongStretch-v4/LongStretch/website/templates/login.html
{% extends "base.html" %}

{% block css%}
<style>
    .divider:after,
    .divider:before {
        content: "";
        flex: 1;
        height: 1px;
        background: #eee;
    }

    .h-custom {
        height: calc(100% - 73px);
    }

    @media (max-width: 450px) {
        .h-custom {
            height: 100%;
        }
    }
</style>
{%endblock%}


{% block content%}


<section class="vh-100 mt4">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                    class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">

                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">

                        <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
                            <p class="lead fw-normal mb-0 me-3">Sign in with</p>

                            <button type="button" class="btn btn-floating mx-0">
                                <img src="{{url_for('static',filename='images/google.png')}}" alt="">
                            </button>
                        </div>

                        <div class="divider d-flex align-items-center my-4">
                            <p class="text-center fw-bold mx-3 mb-0">Or</p>
                        </div>

                        <!-- Email input -->
                        <div class="mb-4 form-group">
                            <b>{{ form.email.label(class="form-label") }}</b>
                            {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}  
                            {{ form.email(class="form-control form-control-lg",placeholder="Enter a valid email address") }}
                            {% endif %}
                        </div>

                        <!-- Password input -->
                        <div class="mb-3">
                            <b>{{ form.password.label(class="form-label") }}</b>
                            {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.password(class="form-control form-control-lg",placeholder="Enter password") }}
                            {% endif %}
                        </div>

                        <div class="d-flex justify-content-between align-items-center">
                            <!-- Checkbox -->
                            <div class="form-check mb-0">
                                {{ form.remember(class="form-check-input me-2") }}
                                {{ form.remember.label(class="form-check-label") }}

                            </div>
                            <a href="#!" class="text-body">Forgot password?</a>
                        </div>
                    </fieldset>
                    <div class="text-center text-lg-start mt-4 pt-2">
                        <div class="form-group">
                            {{ form.submit(class="btn btn-primary btn-lg",style="padding-left: 2.5rem; padding-right: 2.5rem;") }}
                        </div>

                        <!-- <button type="submit" name="loginbutton" class="btn btn-primary btn-lg"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button> -->
                        <p class="small fw-bold mt-2 pt-1 mb-0">
                            Don't have an account?
                            <a href="\register" class="link-danger">Register</a>
                        </p>
                    </div>

                </form>


            </div>
        </div>
    </div>
</section>

{%endblock%}

LongStretch-v4/LongStretch/website/templates/news.html
{% extends "base.html" %}
{% set active_page ='news' %}

{% block css%}
<link rel="stylesheet" href="{{url_for('static',filename='news.css')}}">
{%endblock%}


{% block content%}

<section class="w-100 p-4 " style="background-color: rgb(245, 245, 247)">

    <div class="container">
        <div class="row">
            <h2>"Custom News"</h2>
            <hr class="dropdown-divider">
        </div>
        <div class="row">
            <iframe class="newsfeed-antidope" height="440"  src="https://rss.app/embed/v1/carousel/txiubBsJ79bhp2KT" frameborder="0"></iframe>
        </div>

        <div class="row">
            <h2>Anti-Doping</h2>
            <hr class="dropdown-divider">
        </div>
        <div class="row">
            <iframe class="newsfeed-antidope" height="440"  src="https://rss.app/embed/v1/carousel/txiubBsJ79bhp2KT" frameborder="0"></iframe>
        </div>
        <div class="row">
            <h2>TUE and Doping</h2>
            <hr class="dropdown-divider">
        </div>
        <div class="row">
            <iframe class="newsfeed-tue"src="https://rss.app/embed/v1/list/tO5rF6b2mYnIKw1u" frameborder="0"></iframe>
        </div>
    </div>

</section>

{%endblock%}

LongStretch-v4/LongStretch/website/templates/post.html
{% extends "base.html" %}
{% set active_page ='forum' %}



{% block content%}

<article class="bg-light p-4 m-1 rounded">
    <div class="container">
        <div class="row">
            <div class="col-1">
                <img src="{{url_for('static',filename='images/profile_pic/'+post.author.profile_pic)}}" alt="img"
                    class="rounded-circle" style="width: 50px;">
            </div>
            <div class="col-12">
                <h3 class="">{{post.title}}</h3>
            </div>
            <div class="col-2 ">
                <a class="link-primary" style="text-decoration:none" href="{{url_for('views.account', username=post.author.username)}}">{{post.author.username}}</a>
            </div>
            <div class="col-2 ms-auto ">
                {{post.date_posted.strftime('%Y-%m-%d')}}
            </div>
        </div>
        {% if post.author == current_user %}
        <div class="row">
            <a href="{{url_for('views.update_post',post_id=post.id)}}" class="btn  btn-secondary btn-sm m-1">Update</a>
            <button type="button" class="btn btn-primary btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">
                Delete Post
            </button>
        </div>
        {%endif%}
        <hr class="dropdown-divider">
        <div class="row">
            <p>{{post.content}}</p>
        </div>

    </div>
</article>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Post?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this post? It will be lost forever.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{ url_for('views.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

{%endblock%}

LongStretch-v4/LongStretch/website/templates/register.html
{% extends "base.html" %}

{% block content%}

<div class="container">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">

            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    <div class="border-top pt-3 mt-3">
        <small class="text-muted">
            Already Have An account? <a href="{{url_for('views.login')}}" class="ml-2">Login</a>
        </small>
    </div>
</div>
 

{%endblock%}

LongStretch-v4/LongStretch/website/templates/tue.html
{% extends "base.html" %}
{% set active_page ='tue' %}

{% block content%}


{%endblock%}